pid_ks:
    kp_A: 0.1
    kp_B: 0.1
    kd_A: 0.001
    kd_B: 0.001
    ki_A: 0.0
    ki_B: 0.0
    speed_kA: 0.9
    speed_kB: 0.9
    # kp_A: 0.1
    # kp_B: 0.1
    # kd_A: 0.001
    # kd_B: 0.001
    # ki_A: 0.0
    # ki_B: 0.0
    # speed_kA: 0.9
    # speed_kB: 0.9

check_ready_timeout: 5.0
write_timeout: 1.0
packet_read_timeout: 0.15

drive_command_timeout: 30.0
drive_command_update_delay: 0.0333

joystick_deadzone: 0.1
max_joy_val: 1.0

shutdown_time_limit: 3.0

write_date_delay: 0.5

stepper_max_speed: 250000000
stepper_max_accel: 10000000

drive_max_speed: 6800.0
drive_min_speed: 2500.0

gripper_open: 50
gripper_closed: 180

breakout_level_config: |
    ########
    oooooooo
    ########
    ##oooo##
    ########
