audio_sink: alsa_output.usb-Generic_USB2.0_Device_20130100ph0-00.analog-stereo
volume: 0.25
volume_raw_max: 65536
volume_raw_min: 63119
sounds:
    startup: "/home/ben/Music/sound_effects/ding.wav"
    breakout_brick: "/home/ben/Music/sound_effects/kirby_footstep.wav"
    breakout_win: "/home/ben/Music/sound_effects/Kirby Dance (Short) - Kirby Super Star.mp3"
    breakout_out_of_bounds: "/home/ben/Music/sound_effects/thud.wav"
    breakout_paddle: "/home/ben/Music/sound_effects/kirby_footstep.wav"
    volume_change: "/home/ben/Music/sound_effects/click.wav"
    # bumper_sound: "/home/ben/Music/sound_effects/minecraft_oof.mp3"
    # bumper_sound: "/home/ben/Music/sound_effects/doh.mp3"
    # bumper_sound: "/home/ben/Music/sound_effects/exclamation.wav"
    # bumper_sound: "/home/ben/Music/sound_effects/thud.wav"
    bumper_sound: ""
